version: "3.7"
volumes:
  obds2fhir_data:

services:
  obds2fhir:
    image: docker.verbis.dkfz.de/ccp/obds2fhir:main
    environment:
      #FILE_PATH: "/obds2fhir/clinical_data"
      STORE_PATH: "http://host.docker.internal:8090/fhir"
      #STORE_AUTH: "user:password"
      IDENTIFIER_SYSTEM: "http://dktk.dkfz.de/fhir/onco/core/CodeSystem/PseudonymArtCS"
      #MAINZELLISTE_URL: "http://host.docker.internal:8080"
      #MAINZELLISTE_APIKEY: "pleaseChangeMe"
      #IDTYPE: "pid"
      SALT: "createLocalCustomSalt"
      #SSL_CERTIFICATE_VALIDATION: "true"
      #ADD_DEPARTMENTS: "false"
    volumes:
      - ./clinical_data:/obds2fhir/clinical_data
      #- /etc/bridgehead/traefik-tls:/.../:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"